Repository realm/realm-studio, pull requests merged in 2018-09, with the labels that each got.

#922 Checking validity before accessing parant and their lists
  src/ui/RealmBrowser/Content/index.tsx
  src/ui/RealmBrowser/LeftSidebar/ListFocus.tsx
  src/ui/RealmBrowser/index.tsx
Labels: T:Bug-Crash

#918 Add JWT provider option for login
  src/services/ros/credentials.ts
  src/services/ros/users.ts
  src/ui/ConnectToServer/AuthenticationForm.tsx
  src/ui/ConnectToServer/AuthenticationMethodSelector.tsx
  src/ui/ConnectToServer/ConnectToServer.tsx
  src/ui/ConnectToServer/JwtForm.tsx
  src/ui/ConnectToServer/index.tsx
  src/ui/reusable/RealmLoadingComponent/index.tsx
Labels: T:Enhancement

#933 Adjusting the colors and sizes in the Realm Browser
  src/ui/RealmBrowser/Content/TopBar.tsx
  src/ui/RealmBrowser/LeftSidebar/LeftSidebar.scss
  src/ui/RealmBrowser/LeftSidebar/LeftSidebar.tsx
  src/ui/RealmBrowser/LeftSidebar/ListFocus.tsx
  src/ui/RealmBrowser/RealmBrowser.scss
  styles/variables/_colors.scss
Labels: T:Enhancement

#934 Store and retrieve window size, position and maximized state per type of window
  src/main/Application.ts
  src/main/WindowManager.ts
  src/store.ts
  src/windows/Window.tsx
Labels: T:Enhancement

#941 Click and drag highlighting & cell UI updated
  package-lock.json
  package.json
  src/ui/RealmBrowser/Content/Content.tsx
  src/ui/RealmBrowser/Content/CreateObjectDialog/CreateObjectDialog.scss
  src/ui/RealmBrowser/Content/ResponsiveTable.tsx
  src/ui/RealmBrowser/Content/Table/Cell.tsx
  src/ui/RealmBrowser/Content/Table/ContentGrid.tsx
  src/ui/RealmBrowser/Content/Table/HeaderCell.tsx
  src/ui/RealmBrowser/Content/Table/HeaderGrid.tsx
  src/ui/RealmBrowser/Content/Table/Row.tsx
  src/ui/RealmBrowser/Content/Table/Table.tsx
  src/ui/RealmBrowser/Content/Table/index.tsx
  src/ui/RealmBrowser/Content/Table/rowCellRangeRenderer.tsx
  src/ui/RealmBrowser/Content/Table/types/DataCell.tsx
  src/ui/RealmBrowser/Content/Table/types/DefaultCell.tsx
  src/ui/RealmBrowser/Content/Table/types/ListCell.tsx
  src/ui/RealmBrowser/Content/Table/types/ListIndexCell.tsx
  src/ui/RealmBrowser/Content/Table/types/ObjectCell.tsx
  src/ui/RealmBrowser/Content/Table/types/StringCell/StringCell.tsx
  src/ui/RealmBrowser/Content/Table/types/StringCell/index.tsx
  src/ui/RealmBrowser/Content/Table/types/parser.ts
  src/ui/RealmBrowser/Content/index.tsx
  src/ui/RealmBrowser/RealmBrowser.scss
  src/ui/RealmBrowser/parsers.ts
  src/ui/ServerAdministration/RealmsTable/StateSizeHeader/StateSizeHeader.tsx
  src/ui/ServerAdministration/RealmsTable/StateSizeHeader/index.tsx
Labels: T:Enhancement

#952 Add requirements section
  docs/CONTRIBUTING.md
Labels: T:Doc
