Repository realm/realm-studio, pull requests merged in 2018-10, with the labels that each got.

#957 Fix release build
  Jenkinsfile.release
Labels: T:Internal

#951 Prepare for a new realm-js upgrade
  package-lock.json
  package.json
  src/services/ros/users.ts
  src/ui/ServerAdministration/index.tsx
Labels: T:Enhancement

#961 Highlight cells only when getting focus and not already highlighted
  src/ui/RealmBrowser/Content/Table/Cell.tsx
Labels: T:Bug

#969 Indicate whether a property is primary key in the browser
  src/ui/RealmBrowser/Content/Table/HeaderCell.tsx
  src/ui/RealmBrowser/index.tsx
Labels: G:Rangers, T:Enhancement

#973 Serialize users rather than logging them in again and again
  src/main/Application.ts
  src/main/WindowManager.ts
  src/services/ros/index.ts
  src/services/ros/realms.ts
  src/ui/ConnectToServer/index.tsx
  src/ui/Greeting/index.tsx
  src/ui/ServerAdministration/index.tsx
  src/ui/reusable/RealmLoadingComponent/index.tsx
  src/utils/wait.ts
  src/windows/RealmBrowserWindow.tsx
  src/windows/ServerAdministrationWindow.tsx
Labels: G:Rangers, T:Internal

#974 Prevent upgrading and deletion of system realms
  src/ui/ServerAdministration/RealmsTable/RealmSidebar/SingleRealmContent.tsx
Labels: T:Bug
