Repository realm/realm-studio, pull requests merged in 2018-11, with the labels that each got.

#975 Allow creating users with empty password
  src/ui/ServerAdministration/UsersTable/ChangePasswordDialog/ChangePasswordDialog.tsx
  src/ui/ServerAdministration/UsersTable/CreateUserDialog/CreateUserDialog.tsx
Labels: T:Enhancement

#979 Detect encrypted Realms based on newer Core message
  src/ui/RealmBrowser/index.tsx
Labels: T:Bug

#981 Fix modifying the schema of encrypted Realms
  src/ui/RealmBrowser/AddClassModal/AddClassModal.tsx
  src/ui/RealmBrowser/index.tsx
Labels: T:Bug

#987 Adding a RELEASENOTES.md to the repository + adjusted the prepare script
  Jenkinsfile.prepare
  RELEASENOTES.md
  docs/RELEASENOTES.template.md
  docs/RELEASE_BODY.md
  docs/RELEASING.md
Labels: T:Internal

#988 Updated changelog and releasenotes
  CHANGELOG.md
  Jenkinsfile.prepare
  docs/RELEASENOTES.template.md
Labels: T:Internal

#989 Hide path-level permissions block for Query-based Realms
  src/ui/ServerAdministration/RealmsTable/RealmSidebar/SingleRealmContent.tsx
  src/ui/reusable/Sidebar/Sidebar.scss
Labels: T:Enhancement

#963 Update GettingStarted screen
  src/ui/ServerAdministration/GettingStarted/GettingStarted.tsx
  src/ui/ServerAdministration/GettingStarted/index.tsx
Labels: T:Enhancement

#935 Upgrading to Electron 3.0 + auto updating fixed (again)
  package-lock.json
  package.json
  src/index.d.ts
  src/main/Application.ts
  src/main/Updater.ts
  src/sentry.ts
  src/services/keytar/index.ts
Labels: Blocked, T:Bug

#991 Enforce the default window height as a lower limit when restoring heights
  src/main/WindowManager.ts
Labels: T:Bug

#1000 TSlint updated and errors fixed
  CHANGELOG.md
  package-lock.json
  package.json
  src/main/Updater.ts
  src/main/WindowManager.ts
  src/services/data-importer/csv/CSVSchemaGenerator.ts
  src/services/schema-export/languages/csharp.ts
  src/ui/Greeting/HistoryPanel/HistoryPanel.tsx
  src/ui/RealmBrowser/Bottombar.tsx
  src/ui/RealmBrowser/Content/CreateObjectDialog/types/ListControl.tsx
  src/ui/RealmBrowser/Content/SelectObjectDialog/SelectObjectDialog.tsx
  src/ui/ServerAdministration/GettingStarted/GettingStarted.tsx
  src/ui/ServerAdministration/RealmsTable/RealmSidebar/SingleRealmContent.tsx
  src/ui/ServerAdministration/TopBar/Status.tsx
  src/ui/ServerAdministration/UsersTable/UserSidebar/UserSidebar.tsx
  src/ui/reusable/LoadingOverlay/LoadingOverlay.tsx
Labels: T:Internal

#1004 Downgraded to Electron 2
  RELEASENOTES.md
  package-lock.json
  package.json
  src/main/Application.ts
Labels: T:Bug

#1005 Fixed AM/PM when creating an object with a datetime value
  src/ui/RealmBrowser/Content/CreateObjectDialog/types/DateControl.tsx
Labels: T:Bug

#1010 Cleaning up the package.json (using semver instead of compare-versions)
  RELEASENOTES.md
  package.json
  src/ui/ServerAdministration/RealmsTable/RealmsTable.tsx
  src/ui/ServerAdministration/RealmsTable/index.tsx
  src/ui/ServerAdministration/index.tsx
Labels: T:Internal

#1009 Upgraded reactstrap and its types
  RELEASENOTES.md
  package-lock.json
  package.json
Labels: T:Internal

#1011 Initial application menu update fixed
  RELEASENOTES.md
  src/windows/WindowComponent.tsx
Labels: T:Bug

#1012 Excluding directories when uploading to S3
  Jenkinsfile.release
  RELEASENOTES.md
Labels: T:Internal

#997 Disable analytics in the main process
  RELEASENOTES.md
  package-lock.json
  package.json
  src/main.ts
Labels: T:Internal

#1016 Update CHANGELOG.md
  CHANGELOG.md
  RELEASENOTES.md
  docs/RELEASENOTES.template.md
Labels: T:Internal

#1013 Release artifact upload fixed again
  Jenkinsfile.release
  RELEASENOTES.md
Labels: T:Internal

#1018 Expose UI for blacklisting users
  src/services/ros/index.ts
  src/services/ros/realms.ts
  src/ui/ServerAdministration/UsersTable/UserSidebar/UserSidebar.tsx
  src/ui/ServerAdministration/UsersTable/UserSidebar/UserSidebarContent.tsx
  src/ui/ServerAdministration/UsersTable/UserSidebar/UserStatusRoleTable.scss
  src/ui/ServerAdministration/UsersTable/UserSidebar/UserStatusRoleTable.tsx
  src/ui/ServerAdministration/UsersTable/UserSidebar/index.tsx
  src/ui/ServerAdministration/UsersTable/UsersTable.tsx
  src/ui/ServerAdministration/UsersTable/index.tsx
Labels: T:Feature
