Repository realm/realm-studio, pull requests merged in 2019-03, with the labels that each got.

#1124 Add a GraphiQL browser
  RELEASENOTES.md
  package-lock.json
  package.json
  src/actions/main/Sender.ts
  src/index.d.ts
  src/main/Application.ts
  src/main/MainActions.ts
  src/ui/GraphiqlEditor/GraphiqlEditor.scss
  src/ui/GraphiqlEditor/GraphiqlEditor.tsx
  src/ui/GraphiqlEditor/graphiql-subscriptions-fetcher.ts
  src/ui/GraphiqlEditor/index.tsx
  src/ui/ServerAdministration/RealmsTable/RealmSidebar/RealmSidebar.tsx
  src/ui/ServerAdministration/RealmsTable/RealmSidebar/SingleRealmContent.tsx
  src/ui/ServerAdministration/RealmsTable/RealmSidebar/index.tsx
  src/ui/ServerAdministration/RealmsTable/RealmsTable.tsx
  src/ui/ServerAdministration/RealmsTable/index.tsx
  src/ui/ServerAdministration/ServerAdministration.tsx
  src/ui/ServerAdministration/index.tsx
  src/windows/GraphiqlEditorWindow.tsx
  src/windows/Window.tsx
  src/windows/WindowOptions.ts
  src/windows/WindowProps.ts
Labels: T:Feature

#1128 Prepare version v3.5.0
  CHANGELOG.md
  RELEASENOTES.md
  package-lock.json
  package.json
Labels: T:Internal

#1131 Using react-inspector instead of the deprecated react-object-inspector
  CHANGELOG.md
  RELEASENOTES.md
  docs/RELEASENOTES.template.md
  package-lock.json
  package.json
  src/ResizeObserver.d.ts
  src/index.d.ts
  src/module-wrappers/react-object-inspector.js
  src/ui/ServerAdministration/Log/ContextInspector.tsx
  src/ui/ServerAdministration/Log/Entry.tsx
  src/ui/ServerAdministration/Log/TimestampBadge.tsx
Labels: T:Enhancement
