Repository realm/realm-studio, pull requests merged in 2019-02, with the labels that each got.

#1095 Upgrades and post-packaging tests
  Dockerfile.testing
  Jenkinsfile
  docs/CONTRIBUTING.md
  package-lock.json
  package.json
  src/main/Application.ts
  src/main/Updater.ts
  src/testing/post-packaging/index.ts
  src/testing/post-packaging/mocked-realm-studio/index.js
  src/testing/post-packaging/mocked-realm-studio/package-lock.json
  src/testing/post-packaging/mocked-realm-studio/package.json
  src/testing/post-packaging/mocked-s3-server.ts
  src/ui/RealmBrowser/Content/Table/HeaderCell.tsx
  src/ui/RealmBrowser/Content/Table/index.tsx
  src/ui/RealmBrowser/index.test.tsx
  src/ui/ServerAdministration/TopBar/TopBar.scss
  src/ui/reusable/LoadingDots/LoadingDots.scss
  src/ui/reusable/LoadingDots/index.tsx
  src/windows/WindowOptions.ts
  styles/index.scss
Labels: T:Internal

#1098 Fixing "Open in Studio"
  RELEASENOTES.md
  configs/webpack.main.js
  src/services/ros/users.ts
Labels: T:Bug

#1099 Passing the collection when highlight changes
  src/ui/RealmBrowser/Content/SelectObjectDialog/SelectObjectDialog.tsx
  src/ui/RealmBrowser/Content/SelectObjectDialog/index.tsx
  src/ui/RealmBrowser/Content/index.tsx
Labels: T:Bug

#1100 Visual feedback when filtering in the browser fails
  RELEASENOTES.md
  src/ui/RealmBrowser/Content/Content.tsx
  src/ui/RealmBrowser/Content/TopBar.tsx
  src/ui/RealmBrowser/Content/index.tsx
  src/ui/reusable/QuerySearch/QuerySearch.tsx
  src/ui/reusable/QuerySearch/index.tsx
Labels: T:Enhancement

#1101 Report the studio user agent
  src/renderer.tsx
Labels: T:Internal

#1082 Adding the segfault handler to the renderer processes
  RELEASENOTES.md
  package-lock.json
  package.json
  src/index.d.ts
  src/renderer.tsx
Labels: T:Internal

#1108 Column resizing fixed
  CHANGELOG.md
  RELEASENOTES.md
  docs/RELEASENOTES.template.md
  package-lock.json
  src/ui/RealmBrowser/Content/Table/HeaderCell.tsx
  src/ui/RealmBrowser/Content/Table/index.tsx
  src/ui/RealmBrowser/focus.ts
  src/ui/RealmBrowser/index.tsx
Labels: T:Bug

#1109 Prepare version v3.4.0
  CHANGELOG.md
  RELEASENOTES.md
  package-lock.json
  package.json
Labels: T:Internal

#1113 Fixed various packaging issues
  package-lock.json
  package.json
  src/renderer.tsx
Labels: T:Internal

#1122 Pinning webpack and rebuilding package-lock
  RELEASENOTES.md
  package-lock.json
  package.json
Labels: T:Internal
