Repository realm/realm-studio, pull requests merged in 2019-09, with the labels that each got.

#1167 Updating Prettier & committing fixes
  package-lock.json
  package.json
  src/main/CertificateManager.ts
  src/main/CloudManager.ts
  src/services/data-importer/csv/CSVDataImporter.ts
  src/services/schema-export/languages/csharp.ts
  src/ui/Greeting/MarketingPanel/MessageSlide.tsx
  src/windows/CloudAuthenticationWindow.tsx
  src/windows/ConnectToServerWindow.tsx
  src/windows/GraphiqlEditorWindow.tsx
  src/windows/ServerAdministrationWindow.tsx
Labels: T-Internal

#1173 Upgraded multiple dependencies
  docs/DEPENDENCIES.md
  package-lock.json
  package.json
  src/ui/RealmBrowser/index.test.tsx
Labels: T-Internal

#1175 Downgraded react-inspector to v2.2.2
  docs/DEPENDENCIES.md
  package-lock.json
  package.json
Labels: T-Internal

#1176 Upgraded Reactstrap to v8
  package-lock.json
  package.json
Labels: T-Internal

#1180 Object level permission when filtered or sorted
  RELEASENOTES.md
  src/ui/RealmBrowser/Content/Content.tsx
  src/ui/RealmBrowser/Content/PermissionSidebar/ObjectPermissionSidebar.tsx
  src/ui/RealmBrowser/Content/PermissionSidebar/index.tsx
Labels: T-Bug

#1181 Java & Kotlin schema export fixed
  RELEASENOTES.md
  src/services/schema-export/languages/java.ts
  src/services/schema-export/languages/kotlin.ts
  src/services/schema-export/tests/models/all/java/LinkTypes.java
  src/services/schema-export/tests/models/all/java/RequiredTypes.java
  src/services/schema-export/tests/models/all/kotlin/LinkTypes.kt
  src/services/schema-export/tests/models/all/kotlin/RequiredTypes.kt
  src/services/schema-export/tests/models/sample/java/SampleTypes.java
  src/services/schema-export/tests/models/sample/kotlin/SampleTypes.kt
  src/services/schema-export/utils.ts
Labels: T-Bug

#1184 Hash the server url along with user id
  RELEASENOTES.md
  src/services/ros/realms.ts
Labels: T-Bug

#1185 Implemented TypeScript schema export
  RELEASENOTES.md
  src/services/schema-export/index.ts
  src/services/schema-export/languages/javascript.ts
  src/services/schema-export/languages/typescript.ts
  src/services/schema-export/tests/index.test.ts
  src/services/schema-export/tests/models/all/ts/AllTypes.ts.unformatted
  src/services/schema-export/tests/models/sample/ts/SampleTypes.ts.unformatted
  src/ui/RealmBrowser/index.tsx
Labels: T-Enhancement
