Repository realm/realm-studio, pull requests merged in 2019-10, with the labels that each got.

#1189 Fixed showing fatal errors
  RELEASENOTES.md
  src/ui/reusable/RealmLoadingComponent/index.tsx
Labels: T-Bug

#1177 Upgrading to Realm 3.2.0
  RELEASENOTES.md
  package-lock.json
  package.json
  scripts/next-version.js
Labels: T-Internal

#1192 Fixing documentation urls
  RELEASENOTES.md
  src/ui/ServerAdministration/GettingStarted/GettingStarted.tsx
  src/ui/ServerAdministration/GettingStarted/index.tsx
Labels: T-Doc

#1194 Revert "Upgrading to Realm 3.2.0"
  package-lock.json
  package.json
  scripts/next-version.js
Labels: T-Bug

#1196 Upgrading Realm JS to v3.3.0
  package-lock.json
  package.json
Labels: T-Internal

#1198 Prepare version v3.9.0
  CHANGELOG.md
  RELEASENOTES.md
  package-lock.json
  package.json
Labels: T-Internal
