Repository realm/realm-studio, pull requests merged in 2019-01, with the labels that each got.

#1061 Better error dialogs
  RELEASENOTES.md
  src/ui/reusable/errors.ts
Labels: T:Enhancement

#1062 Read-Only partial realms
  RELEASENOTES.md
  src/ui/RealmBrowser/Content/index.tsx
  src/ui/RealmBrowser/LeftSidebar/LeftSidebar.scss
  src/ui/RealmBrowser/LeftSidebar/LeftSidebar.tsx
  src/ui/RealmBrowser/LeftSidebar/index.tsx
  src/ui/RealmBrowser/RealmBrowser.tsx
  src/ui/RealmBrowser/index.tsx
  src/ui/ServerAdministration/index.tsx
  src/windows/RealmBrowserWindow.tsx
Labels: T:Internal

#1063 Updated wording when opening a partial Realm
  RELEASENOTES.md
  src/ui/ServerAdministration/index.tsx
Labels: T:Internal

#1066 Refactoring singleton windows
  RELEASENOTES.md
  src/main/Application.ts
  src/main/WindowManager.ts
  src/windows/RealmBrowserWindow.tsx
  src/windows/ServerAdministrationWindow.tsx
  src/windows/Window.tsx
Labels: T:Internal

#1067 Check cloud token expiration before it gets used
  RELEASENOTES.md
  package-lock.json
  package.json
  src/main/CloudManager.ts
  src/services/raas/user.ts
  src/ui/Greeting/index.tsx
Labels: T:Bug

#1069 Update Jenkinsfile
  CHANGELOG.md
  Jenkinsfile
  Jenkinsfile.prepare
  docs/RELEASING.md
  package-lock.json
  package.json
  scripts/copy-version-to-lock.js
  scripts/github-releases.js
  scripts/next-version.js
  scripts/tools.js
  scripts/utils.js
Labels: T:Internal

#1073 CI refactored (continued)
  Jenkinsfile
  Jenkinsfile.release
  RELEASENOTES.md
Labels: T:Internal

#1074 Prepare version v3.3.0
  CHANGELOG.md
  RELEASENOTES.md
  package-lock.json
  package.json
Labels: T:Internal

#1083 Updating Realm JS to 2.22.0
  RELEASENOTES.md
  package-lock.json
  package.json
  src/ui/RealmBrowser/index.tsx
  src/ui/RealmBrowser/schema-utils.ts
  src/ui/ServerAdministration/AdminRealm.ts
  src/ui/ServerAdministration/MetricsRealm.ts
  src/ui/ServerAdministration/index.tsx
Labels: T:Internal
