Repository realm/realm-studio, pull requests merged in 2024-06, with the labels that each got.

#1651 RSTUDIO-528: Update version to add support for collections in mixed
  .github/workflows/prs-lint-build-package.yml
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cla: yes

#1654 RSTUDIO-538: Switch to the sass library
  configs/webpack.renderer.js
  package-lock.json
  package.json
  src/ui/ConnectToServer/ConnectToServer.scss
  src/ui/Greeting/Greeting.scss
  src/ui/Greeting/MarketingPanel/MarketingPanel.scss
  src/ui/RealmBrowser/Content/CreateObjectDialog/CreateObjectDialog.scss
  src/ui/RealmBrowser/LeftSidebar/LeftSidebar.scss
  src/ui/RealmBrowser/RealmBrowser.scss
  src/ui/reusable/Sidebar/Sidebar.scss
  src/ui/reusable/Sidebar/variables.scss
  src/windows/SentryErrorBoundary/ErrorOverlay.scss
Labels: cla: yes

#1655 Prepare for 15.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cla: yes, no-jira-ticket

#1656 Fix release
  .github/workflows/publish-release.yml
Labels: cla: yes

#1657 Revert "Prepare for 15.1.0 (#1655)"
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cla: yes

#1658 Prepare for 15.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cla: yes, no-jira-ticket

#1659 Build only Mac x64 for the current releases
  .github/workflows/publish-release.yml
  CHANGELOG.md
  docs/RELEASING.md
Labels: cla: yes, no-changelog, no-jira-ticket

#1661 Prepare for 15.1.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cla: yes, no-jira-ticket

#1663 RSTUDIO-539: Better visualization for mixed and dictionaries
  CHANGELOG.md
  src/ui/RealmBrowser/Content/Table/types/DictionaryCell.tsx
  src/ui/RealmBrowser/JsonViewerDialog/JsonViewerDialog.tsx
  src/ui/RealmBrowser/display.ts
  src/utils/json.ts
Labels: cla: yes

#1664 Prepare for 15.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cla: yes, no-jira-ticket

#1666 RSTUDIO-540: Fix connect to server
  CHANGELOG.md
  src/ui/ConnectToServer/ConnectToServer.tsx
  src/ui/ConnectToServer/index.tsx
  src/ui/reusable/RealmLoadingComponent/index.tsx
Labels: cla: yes

#1667 Prepare for 15.2.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cla: yes, no-jira-ticket
